// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consuming/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryResultRequest is the request type for the Query/Result RPC method
type QueryResultRequest struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryResultRequest) Reset()         { *m = QueryResultRequest{} }
func (m *QueryResultRequest) String() string { return proto.CompactTextString(m) }
func (*QueryResultRequest) ProtoMessage()    {}
func (*QueryResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{0}
}
func (m *QueryResultRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryResultRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultRequest.Merge(m, src)
}
func (m *QueryResultRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultRequest proto.InternalMessageInfo

func (m *QueryResultRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// QueryResultResponse is the response type for the Query/Result RPC method
type QueryResultResponse struct {
	// pagination defines an optional pagination for the request.
	Result *OracleResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryResultResponse) Reset()         { *m = QueryResultResponse{} }
func (m *QueryResultResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResultResponse) ProtoMessage()    {}
func (*QueryResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{1}
}
func (m *QueryResultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryResultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultResponse.Merge(m, src)
}
func (m *QueryResultResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultResponse proto.InternalMessageInfo

func (m *QueryResultResponse) GetResult() *OracleResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// QueryLatestRequestIdRequest
type QueryLatestRequestIdRequest struct {
}

func (m *QueryLatestRequestIdRequest) Reset()         { *m = QueryLatestRequestIdRequest{} }
func (m *QueryLatestRequestIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestRequestIdRequest) ProtoMessage()    {}
func (*QueryLatestRequestIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{2}
}
func (m *QueryLatestRequestIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestRequestIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestRequestIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestRequestIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestRequestIdRequest.Merge(m, src)
}
func (m *QueryLatestRequestIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestRequestIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestRequestIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestRequestIdRequest proto.InternalMessageInfo

// QueryLatestRequestIdResponse
type QueryLatestRequestIdResponse struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryLatestRequestIdResponse) Reset()         { *m = QueryLatestRequestIdResponse{} }
func (m *QueryLatestRequestIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestRequestIdResponse) ProtoMessage()    {}
func (*QueryLatestRequestIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{3}
}
func (m *QueryLatestRequestIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestRequestIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestRequestIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestRequestIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestRequestIdResponse.Merge(m, src)
}
func (m *QueryLatestRequestIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestRequestIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestRequestIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestRequestIdResponse proto.InternalMessageInfo

func (m *QueryLatestRequestIdResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryResultRequest)(nil), "bandprotocol.starportconsumer.consuming.QueryResultRequest")
	proto.RegisterType((*QueryResultResponse)(nil), "bandprotocol.starportconsumer.consuming.QueryResultResponse")
	proto.RegisterType((*QueryLatestRequestIdRequest)(nil), "bandprotocol.starportconsumer.consuming.QueryLatestRequestIdRequest")
	proto.RegisterType((*QueryLatestRequestIdResponse)(nil), "bandprotocol.starportconsumer.consuming.QueryLatestRequestIdResponse")
}

func init() { proto.RegisterFile("consuming/query.proto", fileDescriptor_38b0adbddb76ede3) }

var fileDescriptor_38b0adbddb76ede3 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xe3, 0x40,
	0x1c, 0xc6, 0x9b, 0x2e, 0x5b, 0xd8, 0xd9, 0xc3, 0xc2, 0x2c, 0xbb, 0x48, 0x6c, 0x87, 0x12, 0x44,
	0x45, 0x30, 0x43, 0x5b, 0x3c, 0x55, 0x2f, 0xa2, 0x87, 0x82, 0x22, 0x16, 0xbc, 0x78, 0x29, 0x93,
	0x64, 0x88, 0x81, 0x74, 0x26, 0x9d, 0x99, 0x88, 0x45, 0xbc, 0xf8, 0x04, 0x82, 0x8f, 0xe1, 0x6b,
	0x78, 0xf0, 0x58, 0xf0, 0xe2, 0x51, 0x5a, 0x1f, 0xc3, 0x83, 0x38, 0x93, 0x9a, 0xaa, 0x45, 0xaa,
	0xde, 0x86, 0x7f, 0xbe, 0xef, 0xfb, 0xff, 0xbe, 0x7f, 0xc0, 0x3f, 0x9f, 0x33, 0x99, 0x76, 0x23,
	0x16, 0xe2, 0x5e, 0x4a, 0x45, 0xdf, 0x4d, 0x04, 0x57, 0x1c, 0x2e, 0x79, 0x84, 0x05, 0xfa, 0xe9,
	0xf3, 0xd8, 0x95, 0x8a, 0x88, 0x84, 0x0b, 0x65, 0xb4, 0x54, 0xb8, 0x2f, 0x26, 0xbb, 0x1c, 0x72,
	0x1e, 0xc6, 0x14, 0x93, 0x24, 0xc2, 0x84, 0x31, 0xae, 0x88, 0x8a, 0x38, 0x93, 0x26, 0xc6, 0x5e,
	0xf1, 0xb9, 0xec, 0x72, 0x89, 0x3d, 0x22, 0xa9, 0xc9, 0xc7, 0xc7, 0x35, 0x8f, 0x2a, 0x52, 0xc3,
	0x09, 0x09, 0x23, 0xa6, 0xc5, 0x99, 0xf6, 0x7f, 0x4e, 0xc2, 0x05, 0xf1, 0x63, 0x6a, 0xe6, 0x4e,
	0x03, 0xc0, 0xfd, 0x67, 0x67, 0x9b, 0xca, 0x34, 0x56, 0x6d, 0xda, 0x4b, 0xa9, 0x54, 0xb0, 0x02,
	0x80, 0x30, 0xcf, 0x4e, 0x14, 0xcc, 0x59, 0x55, 0x6b, 0xf9, 0x47, 0xfb, 0x57, 0x36, 0x69, 0x05,
	0x4e, 0x00, 0xfe, 0xbe, 0x32, 0xc9, 0x84, 0x33, 0x49, 0xe1, 0x2e, 0x28, 0x09, 0x3d, 0xd1, 0x8e,
	0xdf, 0xf5, 0x35, 0x77, 0xc6, 0x9e, 0xee, 0x9e, 0x46, 0xca, 0xe2, 0xb2, 0x10, 0xa7, 0x02, 0xe6,
	0xf5, 0x96, 0x1d, 0xa2, 0xa8, 0x1c, 0xa3, 0xb5, 0x82, 0xec, 0xe1, 0x6c, 0x80, 0xf2, 0xf4, 0xcf,
	0x19, 0xcd, 0xc7, 0x1d, 0xea, 0x8f, 0x45, 0xf0, 0x53, 0xfb, 0xe1, 0x95, 0x05, 0x4a, 0x66, 0x35,
	0x6c, 0xce, 0x4c, 0xfc, 0xfe, 0x68, 0xf6, 0xfa, 0xd7, 0xcc, 0x06, 0xd7, 0x59, 0x3c, 0xbf, 0x7d,
	0xb8, 0x2c, 0x56, 0x21, 0xc2, 0xf9, 0x9f, 0x32, 0x87, 0xc0, 0xa7, 0x79, 0x8f, 0x33, 0x78, 0x6d,
	0x81, 0x3f, 0x6f, 0x2a, 0xc3, 0xad, 0xcf, 0x6d, 0x9e, 0x7e, 0x50, 0x7b, 0xfb, 0x9b, 0x29, 0x59,
	0x91, 0x05, 0x5d, 0x04, 0xc1, 0xf2, 0x44, 0x91, 0x58, 0x6b, 0x3b, 0x79, 0x8f, 0xcd, 0x83, 0x9b,
	0x21, 0xb2, 0x06, 0x43, 0x64, 0xdd, 0x0f, 0x91, 0x75, 0x31, 0x42, 0x85, 0xc1, 0x08, 0x15, 0xee,
	0x46, 0xa8, 0x70, 0xd8, 0x0c, 0x23, 0x75, 0x94, 0x7a, 0xae, 0xcf, 0xbb, 0x78, 0x12, 0x08, 0x8f,
	0x81, 0x56, 0xc7, 0x44, 0xf8, 0x64, 0x62, 0x85, 0xea, 0x27, 0x54, 0x7a, 0x25, 0xad, 0x6e, 0x3c,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x72, 0x47, 0xb2, 0x60, 0x79, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	// Request defines a rpc handler method for MsgRequestData.
	Result(ctx context.Context, in *QueryResultRequest, opts ...grpc.CallOption) (*QueryResultResponse, error)
	// LatestRequestId
	LatestRequestId(ctx context.Context, in *QueryLatestRequestIdRequest, opts ...grpc.CallOption) (*QueryLatestRequestIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Result(ctx context.Context, in *QueryResultRequest, opts ...grpc.CallOption) (*QueryResultResponse, error) {
	out := new(QueryResultResponse)
	err := c.cc.Invoke(ctx, "/bandprotocol.starportconsumer.consuming.Query/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestRequestId(ctx context.Context, in *QueryLatestRequestIdRequest, opts ...grpc.CallOption) (*QueryLatestRequestIdResponse, error) {
	out := new(QueryLatestRequestIdResponse)
	err := c.cc.Invoke(ctx, "/bandprotocol.starportconsumer.consuming.Query/LatestRequestId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	// Request defines a rpc handler method for MsgRequestData.
	Result(context.Context, *QueryResultRequest) (*QueryResultResponse, error)
	// LatestRequestId
	LatestRequestId(context.Context, *QueryLatestRequestIdRequest) (*QueryLatestRequestIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Result(ctx context.Context, req *QueryResultRequest) (*QueryResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (*UnimplementedQueryServer) LatestRequestId(ctx context.Context, req *QueryLatestRequestIdRequest) (*QueryLatestRequestIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestRequestId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandprotocol.starportconsumer.consuming.Query/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Result(ctx, req.(*QueryResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestRequestId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestRequestIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestRequestId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandprotocol.starportconsumer.consuming.Query/LatestRequestId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestRequestId(ctx, req.(*QueryLatestRequestIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bandprotocol.starportconsumer.consuming.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Result",
			Handler:    _Query_Result_Handler,
		},
		{
			MethodName: "LatestRequestId",
			Handler:    _Query_LatestRequestId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consuming/query.proto",
}

func (m *QueryResultRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryResultRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryResultRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryResultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryResultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryResultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLatestRequestIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestRequestIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestRequestIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestRequestIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestRequestIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestRequestIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryResultRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryResultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLatestRequestIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestRequestIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryResultRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryResultRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryResultRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryResultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryResultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryResultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &OracleResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestRequestIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestRequestIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestRequestIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestRequestIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestRequestIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestRequestIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
